.TH ABROOT 1 "2023-03-03" "abroot" "User Manual"
.SH NAME
.RS 4
abroot - ABRoot provides full immutability and atomicity by performing transactions between 2 root partitions (A<->B)
.RE
.SH SYNOPSIS
.RS 4
abroot [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
ABRoot provides full immutability and atomicity by performing transactions between 2 root partitions (A<->B)
.RE
.SH OPTIONS
  -v, --verbose   show more detailed output
.PP
.SH ABROOT COMMANDS
.RS 4
\fBget\fP
.RS 4
Outputs the present or future root partition state (A or B)
.PP
.RE
\fBexec\fP
.RS 4
Execute a command in a transactional shell in the future root and switch to it on next boot
.PP
.RE
\fBshell\fP
.RS 4
Enter a transactional shell
.PP
.RE
\fBkargs\fP
.RS 4
Manage kernel parameters\&.
.PP
.RE
\fBdiff\fP
.RS 4
Show modifications from latest transaction\&.
.PP
.RE
\fBrollback\fP
.RS 4
Return the system to a previous state\&.
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/abroot/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH ABROOT SUBCOMMANDS
.SH SUBCOMMAND GET
.RS 4
Outputs the present or future root partition state (A or B)
.RE
.SS SYNOPSIS
.RS 4
\fBget\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Outputs the present or future root partition state (A or B)
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot get present
.PP
abroot get future
.RE
.SH SUBCOMMAND EXEC
.RS 4
Execute a command in a transactional shell in the future root and switch to it on next boot
.RE
.SS SYNOPSIS
.RS 4
\fBexec\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Execute a command in a transactional shell in the future root and switch to it on next boot
.RE
.SS OPTIONS
  -f, --force-run   Force run the command without asking for confirmation
.PP
  -s, --skip-diff   Skip the diff check at the end of the transaction
.PP
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot exec apt-get update
.RE
.SH SUBCOMMAND SHELL
.RS 4
Enter a transactional shell
.RE
.SS SYNOPSIS
.RS 4
\fBshell\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Enter a transactional shell in the future root partition and switch root on the next boot
.RE
.SS OPTIONS
  -f, --force-open   Force open the shell without asking for confirmation
.PP
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot shell
.RE
.SH SUBCOMMAND KARGS
.RS 4
Manage kernel parameters\&.
.RE
.SS SYNOPSIS
.RS 4
\fBkargs\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Manage kernel parameters\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot kargs edit
.PP
abroot kargs get future
.RE
.SH SUBCOMMAND DIFF
.RS 4
Show modifications from latest transaction\&.
.RE
.SS SYNOPSIS
.RS 4
\fBdiff\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
List modifications made to the filesystem in the latest transiction
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot diff
.RE
.SH SUBCOMMAND ROLLBACK
.RS 4
Return the system to a previous state\&.
.RE
.SS SYNOPSIS
.RS 4
\fBrollback\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Executes a system rollback, discarding changes made to the present root\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot rollback
.RE

