.nh
.TH "abroot" "1" "Jan 2023" "VanillaOS/orchid" "abroot Manual"

.SH NAME
.PP
abroot-completion - Generate the autocompletion script for the specified shell


.SH SYNOPSIS
.PP
\fBabroot completion [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for abroot for the specified shell.
See each sub-command's help for details on how to use the generated script.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show more detailed output


.SH SEE ALSO
.PP
\fBabroot(1)\fP, \fBabroot-completion-bash(1)\fP, \fBabroot-completion-fish(1)\fP, \fBabroot-completion-powershell(1)\fP, \fBabroot-completion-zsh(1)\fP
