.nh
.TH "abroot" "1" "Jan 2023" "VanillaOS/orchid" "abroot Manual"

.SH NAME
.PP
abroot-completion-zsh - Generate the autocompletion script for zsh


.SH SYNOPSIS
.PP
\fBabroot completion zsh [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for the zsh shell.

.PP
If shell completion is not already enabled in your environment you will need
to enable it.  You can execute the following once:

.PP
.RS

.nf
echo "autoload -U compinit; compinit" >> ~/.zshrc

.fi
.RE

.PP
To load completions in your current shell session:

.PP
.RS

.nf
source <(abroot completion zsh); compdef _abroot abroot

.fi
.RE

.PP
To load completions for every new session, execute once:

.SS Linux:
.PP
.RS

.nf
abroot completion zsh > "${fpath[1]}/_abroot"

.fi
.RE

.SS macOS:
.PP
.RS

.nf
abroot completion zsh > $(brew --prefix)/share/zsh/site-functions/_abroot

.fi
.RE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for zsh

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show more detailed output


.SH SEE ALSO
.PP
\fBabroot-completion(1)\fP
