.nh
.TH "abroot" "1" "Jan 2023" "VanillaOS/orchid" "abroot Manual"

.SH NAME
.PP
abroot-exec - Execute a command in a transactional shell in the future root and switch to it on next boot


.SH SYNOPSIS
.PP
\fBabroot exec [command] [flags]\fP


.SH DESCRIPTION
.PP
Execute a command in a transactional shell in the future root and switch to it on next boot


.SH OPTIONS
.PP
\fB-y\fP, \fB--assume-yes\fP[=false]
	assume yes to all questions

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for exec


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show more detailed output


.SH EXAMPLE
.PP
.RS

.nf
abroot exec apt-get update

.fi
.RE


.SH SEE ALSO
.PP
\fBabroot(1)\fP
