.nh
.TH "abroot" "1" "Jan 2023" "VanillaOS/orchid" "abroot Manual"

.SH NAME
.PP
abroot-kargs - Manage kernel parameters.


.SH SYNOPSIS
.PP
\fBabroot kargs [edit|get]  [flags]\fP


.SH DESCRIPTION
.PP
Manage kernel parameters.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for kargs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show more detailed output


.SH EXAMPLE
.PP
.RS

.nf
abroot kargs edit
abroot kargs get future

.fi
.RE


.SH SEE ALSO
.PP
\fBabroot(1)\fP
