.nh
.TH "abroot" "1" "Jan 2023" "VanillaOS/orchid" "abroot Manual"

.SH NAME
.PP
abroot-get - Outputs the present or future root partition state (A or B)


.SH SYNOPSIS
.PP
\fBabroot get  [flags]\fP


.SH DESCRIPTION
.PP
Outputs the present or future root partition state (A or B)


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show more detailed output


.SH EXAMPLE
.PP
.RS

.nf
abroot get present
abroot get future

.fi
.RE


.SH SEE ALSO
.PP
\fBabroot(1)\fP
