.nh
.TH "abroot" "1" "Jan 2023" "VanillaOS/orchid" "abroot Manual"

.SH NAME
.PP
abroot - ABRoot provides full immutability and atomicity by performing transactions between 2 root partitions (A<->B)


.SH SYNOPSIS
.PP
\fBabroot [flags]\fP


.SH DESCRIPTION
.PP
ABRoot provides full immutability and atomicity by performing transactions between 2 root partitions (A<->B)


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for abroot

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show more detailed output


.SH SEE ALSO
.PP
\fBabroot-completion(1)\fP, \fBabroot-exec(1)\fP, \fBabroot-get(1)\fP, \fBabroot-kargs(1)\fP, \fBabroot-shell(1)\fP
