.nh
.TH "abroot" "1" "Jan 2023" "VanillaOS/orchid" "abroot Manual"

.SH NAME
.PP
abroot-completion-powershell - Generate the autocompletion script for powershell


.SH SYNOPSIS
.PP
\fBabroot completion powershell [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for powershell.

.PP
To load completions in your current shell session:

.PP
.RS

.nf
abroot completion powershell | Out-String | Invoke-Expression

.fi
.RE

.PP
To load completions for every new session, add the output of the above command
to your powershell profile.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for powershell

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show more detailed output


.SH SEE ALSO
.PP
\fBabroot-completion(1)\fP
