.TH ABROOT 1 "2024-01-21" "abroot" "User Manual"
.SH NAME
.RS 4
abroot - ABRoot provides full immutability and atomicity by performing transactions between 2 root partitions (A<->B)
.RE
.SH SYNOPSIS
.RS 4
abroot [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
ABRoot provides full immutability and atomicity by performing transactions between 2 root partitions (A<->B)
.RE
.SH OPTIONS
  -v, --verbose   show more detailed output
.PP
.SH ABROOT COMMANDS
.RS 4
\fBupgrade\fP
.RS 4
Upgrade the system
.PP
.RE
\fBkargs\fP
.RS 4
Manage kernel parameters
.PP
.RE
\fBpkg\fP
.RS 4
Manage packages
.PP
.RE
\fBrollback\fP
.RS 4
Return the system to a previous state
.PP
.RE
\fBstatus\fP
.RS 4
Display status
.PP
.RE
\fBupdate-initramfs\fP
.RS 4
Update the initramfs
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/abroot/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH ABROOT SUBCOMMANDS
.SH SUBCOMMAND UPGRADE
.RS 4
Upgrade the system
.RE
.SS SYNOPSIS
.RS 4
\fBupgrade\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Check for a new system image and apply it\&.
.RE
.SS OPTIONS
  -c, --check-only   check for updates but do not apply them
.PP
  -d, --dry-run      perform a dry run of the operation
.PP
  -f, --force        force update even if the system is up to date
.PP
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot upgrade
.RE
.SH SUBCOMMAND KARGS
.RS 4
Manage kernel parameters
.RE
.SS SYNOPSIS
.RS 4
\fBkargs\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Manage kernel parameters\&.
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot kargs edit
.RE
.SH SUBCOMMAND PKG
.RS 4
Manage packages
.RE
.SS SYNOPSIS
.RS 4
\fBpkg\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Install and manage packages\&.
.RE
.SS OPTIONS
  -d, --dry-run                       perform a dry run of the operation
.PP
  -f, --force-enable-user-agreement   force enable user agreement, for embedded systems
.PP
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot pkg add <pkg>
.RE
.SH SUBCOMMAND ROLLBACK
.RS 4
Return the system to a previous state
.RE
.SS SYNOPSIS
.RS 4
\fBrollback\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Executes a system rollback, discarding changes made to the present root\&.
.RE
.SS OPTIONS
  -c, --check-only   rollback\&.checkOnlyFlag
.PP
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot rollback
.RE
.SH SUBCOMMAND STATUS
.RS 4
Display status
.RE
.SS SYNOPSIS
.RS 4
\fBstatus\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Display the current ABRoot status\&.
.RE
.SS OPTIONS
  -d, --dump   Dump the ABRoot status to an archive
.PP
  -j, --json   Show output in JSON format
.PP
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot status
.RE
.SH SUBCOMMAND UPDATE-INITRAMFS
.RS 4
Update the initramfs
.RE
.SS SYNOPSIS
.RS 4
\fBupdate-initramfs\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Update the initramfs of the future root\&.
.RE
.SS OPTIONS
  -d, --dry-run   updateInitramfs\&.dryRunFlag
.PP
.SS GLOBAL OPTIONS
  -v, --verbose   show more detailed output
.PP
.SS EXAMPLES
.RS 4
abroot update-initramfs
.RE

